<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-48CJMGQ" ignored="0" name="RetryMulitpleFailedTestCases" tests="6" failures="1" timestamp="18 Feb 2018 01:17:39 GMT" time="0.102" errors="0">
  <testcase name="Test1" time="0.017" classname="TestNG_Annotations.RetryLogic_Class">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.004" classname="TestNG_Annotations.RetryLogic_Class">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="TestNG_Annotations.RetryLogic_Class">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="TestNG_Annotations.RetryLogic_Class">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<false> but was:<true>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:149)
	at junit.framework.Assert.assertEquals(Assert.java:155)
	at TestNG_Annotations.RetryLogic_Class.Test1(RetryLogic_Class.java:11)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.009" classname="TestNG_Annotations.RetryLogic_Class"/>
  <testcase name="Test3" time="0.007" classname="TestNG_Annotations.RetryLogic_Class"/>
</testsuite> <!-- RetryMulitpleFailedTestCases -->
