<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-48CJMGQ" name="InterviewQuestions.TestNG_Annotations" tests="9" failures="0" timestamp="15 Feb 2018 03:44:02 GMT" time="0.076" errors="1">
  <testcase name="TestMethod1" time="0.009" classname="InterviewQuestions.TestNG_Annotations"/>
  <testcase name="TestMethod2" time="0.008" classname="InterviewQuestions.TestNG_Annotations"/>
  <testcase name="TestMethod3" time="0.004" classname="InterviewQuestions.TestNG_Annotations"/>
  <testcase name="TestMethod3" time="0.017" classname="InterviewQuestions.TestNG_Annotations"/>
  <testcase name="TestMethod3" time="0.004" classname="InterviewQuestions.TestNG_Annotations"/>
  <testcase name="TestMethod3" time="0.006" classname="InterviewQuestions.TestNG_Annotations"/>
  <testcase name="TestMethod3" time="0.013" classname="InterviewQuestions.TestNG_Annotations"/>
  <testcase name="TestMethod4" time="0.007" classname="InterviewQuestions.TestNG_Annotations"/>
  <testcase name="TestMethod5" time="0.008" classname="InterviewQuestions.TestNG_Annotations">
    <error type="org.testng.TestException" message="
Method TestNG_Annotations.TestMethod5()[pri:5, instance:InterviewQuestions.TestNG_Annotations@6d4b1c02] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method TestNG_Annotations.TestMethod5()[pri:5, instance:InterviewQuestions.TestNG_Annotations@6d4b1c02] should have thrown an exception of type class java.lang.NumberFormatException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TestMethod5 -->
</testsuite> <!-- InterviewQuestions.TestNG_Annotations -->
